# Generated by Django 3.0.1 on 2019-12-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("id", models.URLField(primary_key=True, serialize=False)),
                ("published", models.DateTimeField()),
                ("title", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("council_area", models.CharField(max_length=255)),
                ("alert_level", models.CharField(max_length=255)),
                ("fire_status", models.CharField(max_length=255)),
                ("fire_type", models.CharField(max_length=255)),
                ("fire_size", models.PositiveIntegerField()),
                ("fire_agency", models.CharField(max_length=255)),
            ],
        ),
    ]
