# Generated by Django 3.0.1 on 2020-01-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firelocs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="latitude",
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="longitude",
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
    ]
