# Generated by Django 3.0.1 on 2020-01-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firelocs', '0002_add_latlng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='alert_level',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='fire_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=20, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=20, default=0),
            preserve_default=False,
        ),
    ]
